from typing import Dict, List
import os
import re
from subprocess import call
from pathlib import Path
from shutil import which

"""
This script automates the generation of .ll test files from C/C++ source files.

It will attempt to preserve FileCheck comments from existing .ll files
by extracting them before replacing the .ll files with new ones generated by clang.
"""

# Define command regex patterns for FileCheck comments
FILECHECK_DIRECTIVES: List[str] = [
    # Execution directives
    r"^; RUN:.*",
    # Output verification directives
    r"^; CHECK:.*",
    r"^; CHECK-NEXT:.*",
    r"^; CHECK-NOT:.*",
    r"^; CHECK-LABEL:.*",
    r"^; CHECK-DAG:.*",
    r"^; CHECK-SAME:.*",
    r"^; CHECK-EMPTY:.*",
    r"^; CHECK-COUNT-\d+:.*",
    # Test configuration directives
    r"^; XFAIL:.*",
    r"^; REQUIRES:.*",
    r"^; UNSUPPORTED:.*",
    # Substitution directives
    r"^; DEFINE:.*",
    r"^; REDEFINE:.*",
    # Other directives
    r"^; X32:.*",
    r"^; X64:.*",
    r"^; COM:.*",
]

CLANG: str = "clang-15"
OPT: str = "opt"
# output to the folder where this script is located
THIS_FILE_DIR: Path = Path(os.path.dirname(os.path.realpath(__file__)))
LL_DIR: Path = THIS_FILE_DIR
SOURCE_DIR: Path = THIS_FILE_DIR / "c"


def extract_filecheck_comments(ll_file: Path) -> List[str]:
    """Extract FileCheck comments from an LLVM IR file"""
    with ll_file.open("r") as f:
        lines = f.readlines()
    filecheck_comments = [
        line
        for line in lines
        if any(re.match(pattern, line) for pattern in FILECHECK_DIRECTIVES)
    ]
    pp_llvm_lit_lines = "\n".join([f"\t{s.strip()}" for s in filecheck_comments])
    print(
        f"Extracting the following llvm-lit comments from {ll_file}:\n{pp_llvm_lit_lines}"
    )
    return filecheck_comments


def extract_compile_cmds_from_c_file(
    c_file_path: Path
) -> List[str]:
    """
    Extracts compile commands from a C source file based on // @COMPILE-CMD: comments.
    Replaces $THIS, $CLANG, $OPT, $OUTPUT_DIR with their respective values.
    Returns a list of commands in the order they appear.
    """
    commands = []
    with c_file_path.open("r") as f:
        for line in f:
            line = line.strip()
            if line.startswith("// @COMPILE-CMD:"):
                cmd = line[len("// @COMPILE-CMD:"):].strip()
                replacements = [
                    ("$OUTPUT_DIR", str(LL_DIR.resolve())),
                    ("$OUTPUT", str(c_file_to_ll_file(c_file_path).resolve())),
                    ("$THIS", str(c_file_path.resolve())),
                    ("$CLANG", CLANG),
                    ("$OPT", OPT),
                ]
                for var, value in replacements:
                    # Only replace if variable is surrounded by non-word characters or at boundaries
                    cmd = re.sub(rf'(?<!\w){re.escape(var)}(?!\w)', value, cmd)
                commands.append(cmd)
    return commands


def c_file_to_ll_file(c_file_path: Path) -> Path:
    """
    Given a .c file path, return the corresponding .ll file path in LL_DIR.
    """
    return LL_DIR / (c_file_path.stem + ".ll")


def list_source_files() -> List[Path]:
    """
    Returns a list of all .c and .cpp file paths located in source_dir.
    """
    return [p for p in SOURCE_DIR.glob("**/*") if p.suffix in {".c", ".cpp"} and p.is_file()]


def build():
    """
    For each C/CPP file in SOURCE_DIR:
      - Extract compile commands
      - Convert to .ll path
      - If .ll exists, extract FileCheck comments
      - Run compile commands sequentially
      - Insert FileCheck comments at the top of the new .ll file
    """
    for c_file in list_source_files():
        compile_cmds = extract_compile_cmds_from_c_file(c_file)
        ll_file = c_file_to_ll_file(c_file)
        filecheck_comments = []
        if ll_file.exists():
            filecheck_comments = extract_filecheck_comments(ll_file)
        # Run compile commands
        for cmd in compile_cmds:
            print(f"Running: {cmd}")
            ret = call(cmd, shell=True)
            if ret != 0:
                print(f"Command failed: {cmd}")
                break
        # Insert FileCheck comments at the top of the .ll file
        if filecheck_comments and ll_file.exists():
            with ll_file.open("r") as f:
                ll_contents = f.readlines()
            with ll_file.open("w") as f:
                f.writelines(filecheck_comments)
                # Ensure a blank line between comments and IR if not already present
                if filecheck_comments and (not ll_contents or ll_contents[0].strip()):
                    f.write("\n")
                f.writelines(ll_contents)


if __name__ == "__main__":
    print(f".ll test folder: {LL_DIR.resolve()}")

    for program in [CLANG, OPT]:
        if which(program) is None:
            raise EnvironmentError(f"Program '{program}' not found in PATH. Please install it or adjust your PATH.")
        print(f"Using {program} at\t{which(program)}")

    if not SOURCE_DIR.exists():
        raise FileNotFoundError(f"Source folder {SOURCE_DIR} does not exist.")
    print(f"Source folder: {SOURCE_DIR.resolve()}")

    print(
        f"FileCheck directives comments will be preserved by extracting them from existing .ll files."
    )

    user_input = input("Do you want to start build? (y/n): ")
    if user_input.lower() == "y":
        build()
    else:
        print("Build not started.")
